services:
    _defaults:
        autowire: true
        autoconfigure: true

    everpsseo.seo.generate_sitemaps:
        class: Everpsseo\Seo\Command\GenerateSitemaps
        public: true
        tags:
            - { name: 'console.command' }

    everpsseo.seo.generate_metas:
        class: Everpsseo\Seo\Command\GenerateMetas
        public: true
        tags:
            - { name: 'console.command' }

    everpsseo.seo.generate_objects_content:
        class: Everpsseo\Seo\Command\GenerateObjectsContent
        public: true
        tags:
            - { name: 'console.command' }

    everpsseo.seo.import:
        class: Everpsseo\Seo\Command\ImportFileCommand
        public: true
        tags:
            - { name: 'console.command' }

    everpsseo.seo.export:
        class: Everpsseo\Seo\Command\ExportFileCommand
        public: true
        tags:
            - { name: 'console.command' }

